bzip2: don't uncompress to stdout
Use just "bzip -d" instead.  Writing to stdout and capturing it in `!'
causes

  Error: string buffer full: #<output port "(string)">

for large log files.